### ISSUE TITLE
stocks don't show on launch if config file update interval is long

### ISSUE THREAD

**Issue by pcause** [tarkah/tickrs#148]
I set my update interval to 600 seconds.  When I launched tickrs before I did this from the cli, stocks started to display right away.  With the interval now set in the config file, no stock data.  I changed the update interval to 20 and started.  I counted off 20 seconds and data began to appear.  This there should be a display on launch and then start using the update interval from when the initial display is completed.

**Comment by JacquardCauseway** [comment]
Same issue on my end. I use a shorter update interval though (60s) so it's not a big deal for me.

**Comment by Xaelias** [comment]
I was trying to look into this and I'm far from an expert in rust or this program. But I'm confused because the code clearly claims to query the data and ask for a draw before the interval is ever evaluated. Which... you can actually see if you show the volumes from the start, since these show up immediately.

All of that to say that I'll keep looking because this annoys me as well but I have no idea what I'm doing 😅

**Comment by tarkah** [comment]
Thanks for the reports. The underlying requests weren't waiting for the crumb data to load before running and waiting for the next update interval, so the initial requests failed due to missing a crumb header and then slept for update interval.

Fixed by #160

**Comment by tarkah** [comment]
Released fix in https://github.com/tarkah/tickrs/releases/tag/v0.14.10
