### ISSUE TITLE
Some symbols always low of zero, resulting in wrong y-axis scaling used

### ISSUE THREAD

**Issue by daniel-j-h** [tarkah/tickrs#22]
Hey hey :wave: it looks like for some symbols (TSLA in the case below) the low is at zero for all time ranges, resulting in plots like the 1D plot to be hard to impossible to read and interpret since we're not "zooming in" on the daily variation.

Here is a screenshot of what I mean. Is this the API sometimes just reporting zero as low? Can we do something in this case?

![tsla](https://user-images.githubusercontent.com/527241/92883325-08f33780-f411-11ea-969a-d385fecee821.jpg)

**Comment by tarkah** [comment]
Thanks for reporting the issue! I'll look into this today.

**Comment by tarkah** [comment]
So I'm calculating the min / max plot points from the data-set to set the y-axis bounds. What appears to be causing your problem is that your current market price is 0, which is causing the min to be 0.

It appears you are having lots of issues fetching data from the API.... you must have a slow / bad connection to wherever the yahoo api servers are located. Along with #23 , I probably should hold off on rendering anything related to the widget until I can guarantee all 3 initial API calls (graph data, current market price, company info) are completed. And as you mentioned, instead put some sort of loading indicator.

**Comment by tarkah** [comment]
I'm going to close this with merging #29
