### ISSUE TITLE
Sometimes no data points shown except high / low

### ISSUE THREAD

**Issue by daniel-j-h** [tarkah/tickrs#23]
Hey hey :wave: It seems like sometimes we can not get any data points other than high / low.

Is this caused by the API? Can this be solved with retries? Should we show a spinner :recycle: or something indicating that we're in the process of fetching the data?

![nodata](https://user-images.githubusercontent.com/527241/92883332-0abcfb00-f411-11ea-9f8f-5f6e29e872e3.jpg)

**Comment by tarkah** [comment]
Yeah what's probably happening is it's grabbing the current market price from the API, but can't grab the graph data. Which is why you only see the 1 dot.

Does the graph data eventually show up? This is probably caused when I deserialize the json response. I'm probably expecting a field that doesn't exist in the response, so I need to make that field optional since it doesn't always come across. I've noticed this API likes randomly omitting certain fields on rare occasion.

**Comment by daniel-j-h** [comment]
Yes, the graph eventually shows up when restarting / reloading. Not entirely sure when this triggers, seems random to me.

**Comment by tarkah** [comment]
As I mentioned in #22, I think this all boils down to network issues fetching against the API. I can see this same view for a micro second before the data loads in from the API. So on top of holding off the render until all data is grabbed and showing a loading indicator, poor connections like yours need some sort of API request retry.

**Comment by tarkah** [comment]
I'm going to close this with merging #29
