### ISSUE TITLE
Futures

### ISSUE THREAD

**Issue by nhsb1** [tarkah/tickrs#31]
Are futures symbols supported?  This may be a case of me just not entering the symbols correctly, but I can't seem to figure it out.  I know Yahoo! does expose the futures here (https://finance.yahoo.com/commodities/).  Taking the S&P ES as an example, (https://finance.yahoo.com/quote/ES%3DF?p=ES%3DF), I've tried variations on the symbol... (ES, ES=F, ES=F?,ES=F?,ES=F?p) to no avail.  

(Also - Very cool tool that you've developed!  I was looking to do something vaguely similar in Python until I came across this).

Thanks!

**Comment by tarkah** [comment]
Yeah, so it appears the API does support it! The reason nothing is showing up is because one of the pieces of API data I'm expecting is missing (luckily nothing critical, just "Company Info" which doesn't relate here). I can easily fix this issue to get things to show up.

In addition, to better support futures, I need to adjust the `1D` chart since it's currently assuming 9am-4pm ET for market hours. Luckily the API tells me the trading hours for any instrument so I can leverage that.

**Comment by tarkah** [comment]
I'll be merging #32 soon to close this out. Here is how it looks:

![image](https://user-images.githubusercontent.com/10239377/93915100-5e0a3580-fcbc-11ea-9716-57c3c1617acc.png)

**Comment by tarkah** [comment]
new release has been published to https://github.com/tarkah/tickrs/releases/tag/v0.7.0. Binaries should be available shortly. I've also released to crates.io
