### ISSUE TITLE
Is it possible to show the volumes too?

### ISSUE THREAD

**Issue by acarpe** [tarkah/tickrs#43]

**Comment by tarkah** [comment]
I have volume data so this should be doable. I'm afraid out of the box, it won't work well to graph volumes along w/ prices since the y-axis range will be completely different. So I have 2 options I think:

1. Add a keyboard shortcut to "toggle" between prices being graphed and volumes. So only 1 is graphed at a time, so the y-axis can adjust accordlingly.
2. Normalize volumes against the min / max of the prices so I can graph it alongside the price graph. There won't be any axis labels to reference for volumes however.

The other thing is I'd prefer to do bar graphs for volumes, which the TUI library I'm using supports, but it'd have to be a separate graph from the price movement. I'll play around with all 3 of these ideas and see what works best, might take me a little while to tackle.

**Comment by acarpe** [comment]
Great! Thank you for the quick response :)
If I can express a preference I'd vote for option 3.

**Comment by tarkah** [comment]
Here are a few rough mockups, I still need to add some logic to make sure the bars extend the entire width perfectly. There's a bunch of caveats, but it's at least a good indicator of volume trends. Since I need to draw distinct bars, the "timeframe" of each bar is dependent on how wide your terminal is.

Do you like it better when the bars are clipped by the price lines? Or where the bars overlap with price lines?

![Code_BgA5vAh5UW](https://user-images.githubusercontent.com/10239377/106824710-3c409800-6638-11eb-806d-b4776a6611c9.png)
![Code_OMDI66KNlo](https://user-images.githubusercontent.com/10239377/106824708-3ba80180-6638-11eb-89ff-cdc629644015.png)

Do you want to see an axis legend on the right side, similar to the one for prices on the left? Or is having the days total volume in the header along w/ current / high / low price fine?

**Comment by tarkah** [comment]
I'm not thrilled about implementing this kind of bar chart as it's impossible to guarantee accuracy in how I sum volumes together for each "bar". Due to rounding, I'll either always have too few bars to fill the width out, or too many bars for the width, and in either scenario the last bar wont have the same # of datapoints summed for the bar.

The TUI library I'm using is pretty limited with what I'm wanting to accomplish, so I might need to get a bit more low level to build a graph type that I can guarantee renders things more accurately, or I use the same type of line graph for volume as price, which I can guarantee accuracy / rendering behavior with.

**Comment by tarkah** [comment]
Ok, I think I found the better layout... And I figured out the logic to ensure it'll always fit the width. I'll try to add some y-axis legend just like w/ price and clean up the format a little. How do you like this?

![image](https://user-images.githubusercontent.com/10239377/106831513-e7efe500-6644-11eb-82c1-5ee3ed6fb024.png)

![image](https://user-images.githubusercontent.com/10239377/106831649-1b327400-6645-11eb-88f9-68952ed5e8d4.png)

![image](https://user-images.githubusercontent.com/10239377/106831671-25ed0900-6645-11eb-8d3e-977b2ac8a2f1.png)

**Comment by acarpe** [comment]
Looks great! Well done! 🔝

**Comment by tarkah** [comment]
Ok, I've wrapped this up. Will be merging and releasing shortly! Here is what it looks like:

![Screenshot from 2021-02-04 09:37:19](https://user-images.githubusercontent.com/10239377/106932576-c33f5000-66cc-11eb-90ae-a2b714286962.png)
![Screenshot from 2021-02-04 09:37:28](https://user-images.githubusercontent.com/10239377/106932574-c33f5000-66cc-11eb-87c7-78b8555232cd.png)
![Screenshot from 2021-02-04 09:37:42](https://user-images.githubusercontent.com/10239377/106932569-c20e2300-66cc-11eb-82cd-9ed400a09364.png)

**Comment by tarkah** [comment]
I've added a single line volume indicator for summary view when volumes are toggled on:

![Screenshot from 2021-02-04 12:39:37](https://user-images.githubusercontent.com/10239377/106952543-183b9000-66e6-11eb-9b67-8e4ac5bec452.png)

**Comment by acarpe** [comment]
It's perfect! 🥇
